### ISSUE TITLE
[Feature request] Sublime Text 3 support

### ISSUE THREAD

**Issue by Kristinita** [ishu3101/Sublime-LuckyLink#1]
Windows 32-bit 10.0.14393, Sublime Text 3 Build 3126 — LuckyLink not worked for me. I don't see `LuckyLink` command in command palette. Do you plan to support Sublime Text 3?

Thanks.

**Comment by ishu3101** [comment]
Since the LuckyLink Sublime Text Plugin uses the Google Web Search API which has been deprecated and replaced with Custom Search API which requires an API key, it causes this plugin to not work even with Sublime Text 2.

**Comment by Kristinita** [comment]
I write plugin [**KristinitaLuckyLink**](http://kristinita.ru/Programs/KristinitaLuckyLink) with same features for Sublime Text 3.

Thanks for idea!
